# Generated by Django 4.1.5 on 2023-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresopq',
            name='Presentaciones',
            field=models.IntegerField(choices=[[0, '500g'], [1, '1kg'], [2, '2kg'], [3, '5kg'], [4, '10kg'], [5, '25kg'], [6, '50kg'], [7, 'Stick Packs']]),
        ),
        migrations.AlterField(
            model_name='ingresopq',
            name='Productos',
            field=models.IntegerField(choices=[(0, 'Azucar Blanca'), (1, 'Azucar Morena'), (2, 'Azucar Ligero'), (3, 'Azucar Turbinado'), (4, 'Azucar Blanco Organico'), (5, 'Azucar De Coco Organico'), (6, 'Panela'), (7, 'Steviazucar Blanca'), (8, 'Steviazucar Morena'), (9, 'Stevia Panela')]),
        ),
    ]
