# Generated by Django 4.1.5 on 2023-03-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_alter_ingresopq_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopq',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/ingresopq/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ingresopq',
            name='estadodoc',
            field=models.BooleanField(default=False),
        ),
    ]
