# Generated by Django 4.1.5 on 2023-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0005_ingresopq_doc_ingresopq_estadodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapq',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipospq',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
