# Generated by Django 4.1.5 on 2023-03-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0006_alter_categoriapq_nombre_alter_tipospq_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresopq',
            name='lote',
            field=models.CharField(max_length=7),
        ),
    ]
